### ISSUE TITLE
Exception thrown when updated Arrow to 2.0.0 in main app module

### ISSUE THREAD

**Issue by spectrumIG** [nefilim/kjwt#35]
I updated Arrow to 2.0.0-alpha.2 in my main app and after that I have this exception thrown at runtime. This is strange because I already had the Arrow version of this lib and the one I use in the project differs. 
Some suggestions? Thanks

`java.lang.NoClassDefFoundError: Failed resolution of: Larrow/core/computations/either;
	at io.github.nefilim.kjwt.JWT$Companion.decode(JWT.kt:129)
	...
Caused by: java.lang.ClassNotFoundException: Didn't find class "arrow.core.computations.either" on path
`

**Comment by sproctor** [comment]
Unfortunately, it seems that Arrow has used the same namespace for Arrow 2, so they can't coexist. I think you need to stick with arrow 1.x until this library is updated.

**Comment by Atternatt** [comment]
hello @sproctor @nefilim I created this [PR](https://github.com/nefilim/kjwt/pull/39#issue-2828586597) that fixes the issue by migrating to Arrow 2.0.0

If it looks good and can be deployed you would make me a favor 🙏🏻  let me know if there is anything missing that I should fix before.

Thanks!

**Comment by sproctor** [comment]
@Atternatt Thanks for that! I updated my project and it passes my tests.
